In [ ]:
import pandas as pd

movies = pd.read_csv("movies.csv")
ratings = pd.read_csv("ratings.csv")

movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [ ]:
data = pd.merge(ratings, movies, on="movieId")

data.head()

,userId,movieId,rating,timestamp,title,genres
0,1,1,4.0,964982703,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,1,3,4.0,964981247,Grumpier Old Men (1995),Comedy|Romance
2,1,6,4.0,964982224,Heat (1995),Action|Crime|Thriller
3,1,47,5.0,964983815,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
4,1,50,5.0,964982931,"Usual Suspects, The (1995)",Crime|Mystery|Thriller

In [ ]:
movie_matrix = data.pivot_table(
    index="userId",
    columns="title",
    values="rating"
)

movie_matrix = movie_matrix.fillna(0)

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(movie_matrix.T)

In [ ]:
import numpy as np

def recommend(movie_name):

    movie_index = movie_matrix.columns.get_loc(movie_name)

    scores = list(enumerate(similarity[movie_index]))

    scores = sorted(scores, key=lambda x: x[1], reverse=True)

    scores = scores[1:6]

    for i in scores:
        print(movie_matrix.columns[i[0]])

In [ ]:
recommend("Toy Story (1995)")

Toy Story 2 (1999)
Jurassic Park (1993)
Independence Day (a.k.a. ID4) (1996)
Star Wars: Episode IV - A New Hope (1977)
Forrest Gump (1994)

In [ ]:
print(movie_matrix.shape)

(610, 9719)